### PR TITLE
Protocol 6.2

### PR DESCRIPTION
**Pull request by NichUK**
@mathpaquette 

Here's a pass at protocol 6.2 fufilling issue #61.

I believe it's completely functional, and all the tests pass (locally). I have added (and may add some more tests) to better test the new functionality.

Protocol 6.2 additions (details: [from IQ Feed](http://www.iqfeed.net/dev/upgrade.cfm?protocol=1))

- [x] New Level2 messages and events (market by price, market by order)
- [x] Keep access to current Level2 messages (protocol 6.1) for the present - remove them in a future update
- [x] Add Level 1 Trade Corrections data and events
- [x] Handle new Lookup data identifier fields (maintaining compatibility with existing files and data)

Can you have a look please, and let me know if there's anything you particularly dislike or want to discuss!

### CODE REVIEW

**Comment by NichUK** [comment]
I don't think we should be looking to add this to "master" until it's out of beta with IQ, but if you think it's OK, then I'd be quite up for making the protocol_6.2 branch available for people to play with/test with IQ's beta feed.

**Comment by mathpaquette** [comment]
> I don't think we should be looking to add this to "master" until it's out of beta with IQ, but if you think it's OK, then I'd be quite up for making the protocol_6.2 branch available for people to play with/test with IQ's beta feed.

well. it depends... I'm more trunk based development oriented meaning master has all latest changes. Worst case, we can have a protocol6.1 branch and simply not adding this commit or others specific for 6.2

but I think the focus now is really 6.2

**Comment by mathpaquette** [comment]
> @mathpaquette
> 
> Here's a pass at protocol 6.2 fufilling issue #61.
> 
> I believe it's completely functional, and all the tests pass (locally). I have added (and may add some more tests) to better test the new functionality.
> 
> Protocol 6.2 additions (details: [from IQ Feed](http://www.iqfeed.net/dev/upgrade.cfm?protocol=1))
> 
> * [ ]  New Level2 messages and events (market by price, market by order)
> * [ ]  Keep access to current Level2 messages (protocol 6.1) for the present - remove them in a future update
> * [ ]  Add Level 1 Trade Corrections data and events
> * [ ]  Handle new Lookup data identifier fields (maintaining compatibility with existing files and data)
> 
> Can you have a look please, and let me know if there's anything you particularly dislike or want to discuss!

Of course. Thank you so so much!!

**Comment by mathpaquette** [comment]
very interesting stuff!! Wow much more work than I was expected. Ill review in deeper with my IDE but looks great! 
Not sure we need that much backward compatibility for all Parsing logic, maybe we need to sort this out.

**Comment by NichUK** [comment]
The backwards compatibility is only where there may be file data already stored in a previous protocol format. Places where it's online only, are 6.2 only.

**Pull request merged**
