### PR TITLE
Issue #17 Fix

### PR DESCRIPTION
**Pull request by hunterfries**
Reversed Open and Close position in IntervalMessage and DailyWeeklyMonthlyMessage objects

### CODE REVIEW

**Comment by hunterfries** [comment]
Hey can we release 1.4.1 so I can get this fix from nuget?

**Comment by mathpaquette** [comment]
Hunter, check the appveyor build log, packages are deployed automatically on myget

Sent from my iPhone

On Aug 9, 2018, at 6:29 PM, hunterfries <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey can we release 1.4.1 so I can get this fix from nuget?

**Comment by hunterfries** [comment]
I removed and readded the package and the dll is still showing an 8/5 build date..am i missing something?

**Comment by mathpaquette** [comment]
Try this please:

Install-Package IQFeed.CSharpApiClient -Version 1.4.0.151 -Source https://www.myget.org/F/inovitex/api/v3/index.json

Mathieu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by hunterfries** [comment]
Thanks dude. We are good to go. Does nuget just take some time to update? Sorry for the back and forth and sense of urgency…fixing this was in the critical path..thanks for the rapid response!

hunter

**Comment by mathpaquette** [comment]
Welcome Hunter.

In fact, every commits generate a package on myget.. Releases on Nuget are only triggered by merge on the release branch on version increase.

I try to keep as low as possible the number of release on Nuget since we cant really remove them and this generate a lot of mess for the end user 😊

Happy that you appreciate the effort.
Mathieu

**Pull request merged**
