### PR TITLE
New Lookup APIs with tests & other bug fixes

### PR DESCRIPTION
**Pull request by mrut2pac**
1. Added lookup APIs
2. Added unit tests for lookup APIs
3. Added integration tests for lookup APIs
4. Some bug fixes
5. Some failing tests fixes

### CODE REVIEW

**Comment by mathpaquette** [comment]
awesome! ill add my comments very soon. thanks!

**Comment by mathpaquette** [comment]
@mrut2pac I can't merge the PR as is because of the unnecessary merge conflict. Ill give you the procedure to recreate it as it should be.

**Comment by mathpaquette** [comment]
@mrut2pac 
Make sure you have my repo as one of your remotes:
git remote -v

If you don't see `https://github.com/mathpaquette/IQFeed.CSharpApiClient.git` add it as the upstream:
git remote add upstream https://github.com/mathpaquette/IQFeed.CSharpApiClient.git

git fetch upstream
git checkout -b "feat-symbol" "origin/master"
git cherry-pick --no-commit 0f8aa56880283fd3700c84ba18d1e7f0aabc06a2
git cherry-pick --no-commit 10095159b4ee80ff1baa1b2c133ac4d00011b23c
git cherry-pick --no-commit 48cb0d268158d73a6a2ebed8843ea2db288b6d83
git cherry-pick --no-commit b19d10735370cfc84c249a04d78d69d9957e28e0
git add *
git commit -m "feat(lookup/symbol): add support for symbol lookup"

recreate the PR from the feat-symbol branch

thanks

**Comment by mathpaquette** [comment]
@mrut2pac you got my comment on the PR?

**Comment by mrut2pac** [comment]
Yeah. I was actually hoping to get some change suggestions cause I noticed I misspelled NAICS in my changes and wanted to fix it :-) 
If you don’t want any other changes I will fix these in my master, then follow your steps to create a new Pull Request. 

Regards,
Vardan

**Comment by mathpaquette** [comment]
was a bit not practical to start reviewing in because too much files were changed. some slight changes might be required but we can talk about it later.

**Comment by mrut2pac** [comment]
I guess I need to do 
git checkout -b "feat-symbol" "upstream/master" instead or "origin/master"

**Comment by mrut2pac** [comment]
also added git cherry-pick --no-commit 97979cc (my latest commit)

**Comment by mathpaquette** [comment]
> I guess I need to do
> git checkout -b "feat-symbol" "upstream/master" instead or "origin/master"

true

**Comment by mrut2pac** [comment]
Updated the PR, please have a look

**Comment by mathpaquette** [comment]
sure, doing my very last pass before merging 🙂

thanks for all your efforts. this is very much appreciated and will help lots of people
________________________________

**Comment by mrut2pac** [comment]
Thank you for starting it, this already benefits lot of people! :-)

Regards,
Vardan

**Pull request closed without merging**
