### PR TITLE
Messages with serializable attribute, Issue #11

### PR DESCRIPTION
**Pull request by Nucs**
See Issue #11.

### CODE REVIEW

**Comment by mathpaquette** [comment]
@Nucs are you sure that the serialization will work with not setters? I had this issue yesterday.

**Comment by Nucs** [comment]
You are right, I haven't noticed that. properties do not have a public setter.
This might indeed be an issue.

Should I just make all empty constructors public and add a public setter to all properties to widen the support to almost any serialization library?

**Comment by mathpaquette** [comment]
Nope this will break immutability...

Sent from my iPhone

On Aug 24, 2018, at 12:26 PM, Eli Belash <notifications@github.com<mailto:notifications@github.com>> wrote:


You are right, I haven't noticed that. properties do not have a public setter.
This might indeed be an issue.

Should I just make all empty constructors public and add a public setter to all properties to widen the support to almost any serialization library?

**Comment by Nucs** [comment]
Awaiting for you to decide what to do.

**Comment by mathpaquette** [comment]
We're going to postpone this one...

**Pull request closed without merging**
