### PR TITLE
Changed HistoricalDataTimeFormat to match API docs

### PR DESCRIPTION
**Pull request by hunterfries**

### CODE REVIEW

**Comment by mathpaquette** [comment]
@hunterfries in reality build is failing cause unit tests are disabled on AppVeyor.

**Comment by hunterfries** [comment]
I will update the format accordingly.

**Comment by mathpaquette** [comment]
@hunterfries, I think the problem is more related to Culture.Invariant because for timespan there's no HH SS format

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings#the-hh-custom-format-specifier

**Comment by mathpaquette** [comment]
@hunterfries gimme your culture info.

**Comment by hunterfries** [comment]
en-US

Sent from my iPhone

On Mar 17, 2019, at 9:00 PM, Mathieu Paquette <notifications@github.com<mailto:notifications@github.com>> wrote:


@hunterfries<https://github.com/hunterfries> gimme your culture info.

**Comment by mathpaquette** [comment]
@hunterfries the problem is somewhere else.

**Comment by jphiggs** [comment]
Not sure if this is related to @hunterfries' issue but over the weekend I was getting an IQFeed exception when using the BasicHistorical Example for Historical.ReqHistoryIntervalDaysAsync.  The inner exception was "Invalid number of parameters'.  That didn't occur with the other 2 historical requests in step 5 for that example.  The exception also does not occur if I hard code the IQFeed request to 
var request = $"HID,AAPL,300,5,100,,,,,,{IQFeedDefault.ProtocolTerminatingCharacters}"; in the historical request formatter.  Bottom line is that the formatter will include 7 commas for the optional parameters in the request and that is correct according to the IQFeed documenation, but the exception occurs with seven commas and works with 6.  There are also several of the ApiClient tests that are failing for historical requests.

**Pull request closed without merging**
