### PR TITLE
fix(lookup): properly throw for InvalidData

### LINKED ISSUE #122: PeriodVolume doesn't fit in 32 bit integer of IntervalMessage
Hey there.

Some 4-hour candles for C (CITIGROUP) have period volume that doesn't fit in 32 bit integer field of IntervalMessage.
This causes other various problems depending on used API method.

### LINKED ISSUE #124: IQFeed client returns data from previous request
Subsequent requests can return not proceed messages from previous request.
This issue is caused by #122 and can be reproduced if user uses GetIntervalMessages (without RequestId) method.

TryParse returns false in case if it can't parse upcomming message.
image
This means that client doesn't read all messages sent by iqconnect. Next data request to the same client will consume queued (unread) data.

### PR DESCRIPTION
**Pull request by mathpaquette**
- increase IntervalMessage.PeriodVolume to long
- add more info in InvalidDataIQFeedException

fixes #122, fixes #124

### CODE REVIEW

**Comment by mathpaquette** [comment]
@NichUK @mrut2pac not sure it makes sense to change int32 to long for this kind of unique edge case expressed by #122

**Comment by NichUK** [comment]
To be honest, I think that it does make sense. Bar volumes can get awfully big for bars of any significant length.

**Comment by mrut2pac** [comment]
I second that. In my applications I always use long for volume. Especially reasonable for penny & sub-penny stocks :)

**Comment by mathpaquette** [comment]
> To be honest, I think that it does make sense. Bar volumes can get awfully big for bars of any significant length.

well, its very exceptional I will say and it does happen only when you set large interval such 4 hours on very very active stocks.

**Comment by mathpaquette** [comment]
> I second that. In my applications I always use long for volume. Especially reasonable for penny & sub-penny stocks :)

okay lets move to long for IntervalMessage.PeriodVolume as well.

Thanks guys.

**Comment by mathpaquette** [comment]
@NichUK any comments?

**Pull request merged**
