### PR TITLE
Restrict local IP address list to IPv4.

### PR DESCRIPTION
**Pull request by mbmurray**
I simply restrict the list of addresses to those in the IPv4 family.

### CODE REVIEW

**Comment by Nucs** [comment]
@mathpaquette, I would suggest to implement it but also include a static property to either force it to ipv4 or keep it automatic like it is now where automatic is the default.

**Comment by Nucs** [comment]
This is related to issue #35.

**Comment by mbmurray** [comment]
I made the suggested change and resubmitted the pull request.

**Comment by mathpaquette** [comment]
guys, dont forget when you submit a PR, you need to provide some tests to back your changes... cant merge the PR as is...

**Comment by mbmurray** [comment]
Looks like I'll just have to close this pull request then.  The class that was modified doesn't currently have any tests written for it.  It is a class that directly interacts with the computer system and is pretty much un(unit)testable as written.  Refactoring the code to abstract out the interaction points behind an interface seemed to be outside the scope of the initial change.

**Comment by mbmurray** [comment]
I added a few integration tests.

**Comment by mbmurray** [comment]
@mathpaquette , are you going to take a look at this?  I've made all the requested updates.

**Comment by mathpaquette** [comment]
Yes sure Michael I’ll take care soon!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mathpaquette** [comment]
@mbmurray im gonna to fix that slightly differently. integration tests like this are duplicated. we just need to use once... anyway, thanks for reporting the issue!

**Pull request closed without merging**
