### PR TITLE
feat(historical): add TryParse to all historical messages

### LINKED ISSUE #96: Exception inside SocketClient.ProcessReceive is not handled
Hello, yesterday it seems IqFeed sent wrong data which caused the following unhandled exception to be generated:

```
Application: IqFeedManager.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at IQFeed.CSharpApiClient.Lookup.Historical.Messages.TickMessage.Parse(String message)
   at IQFeed.CSharpApiClient.Lookup.Common.BaseLookupMessageHandler.ProcessMessages[T](Func`2 parserFunc, Func`2 errorParserFunc, Byte[] message, Int32 count)
   at IQFeed.CSharpApiClient.Lookup.Historical.HistoricalMessageHandler.GetTickMessages(Byte[] message, Int32 count)
   at IQFeed.CSharpApiClient.Lookup.Common.BaseLookupFacade.<>c__DisplayClass4_0`1.<GetMessagesAsync>g__SocketClientOnMessageReceived|1(Object sender, SocketMessageEventArgs args)
   at IQFeed.CSharpApiClient.Socket.SocketClient.ProcessReceive(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

The exception has been generated in the _IOCompletionCallback thread and wasn't handled in that thread, so it became unhandled exception and crashed the service.

Wrapping the API call which generated the IQFeed call above doesn't catch this exception:

```
try {
 ... await lookupClient.Historical.GetHistoryTickDatapointsAsync(...
} catch (Exception ex) {
...
 // wasn't called
}
```

obviously because there is no any code which marshals this exception from the _IOCompletionCallback thread to the context of calling function.

### PR DESCRIPTION
**Pull request by mathpaquette**
fixes #96

### CODE REVIEW

**Comment by mathpaquette** [comment]
@gribunin @Nucs have a look.

**Review by gribunin — APPROVED** [review]
Good job, much better fits into your existing library paradigm + tests I was too lazy to write.

Can I ask you, how long it's gonna take to get these changes into new version of Nuget package?

**Comment by mathpaquette** [comment]
> Good job, much better fits into your existing library paradigm + tests I was too lazy to write.
> 
> Can I ask you, how long it's gonna take to get these changes into new version of Nuget package?

Cool thanks. I might create a new release today but dont wait for it you can use pre-release Nuget available here:
https://www.myget.org/feed/iqfeedcsharpapiclient/package/nuget/IQFeed.CSharpApiClient

**Comment by mathpaquette** [comment]
> Good job, much better fits into your existing library paradigm + tests I was too lazy to write.
> 
> Can I ask you, how long it's gonna take to get these changes into new version of Nuget package?

@gribunin may I ask you a little star on the project? Thank you for your help on this!

**Pull request merged**
